name: morning
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{wx619beefafd1f1bcd}}
      APP_SECRET: ${{3f0d8e6a4e6bc4f3dd11bc8910553a01}}
      TEMPLATE_ID: ${{oXdd6Cm-BHHyhxYKGtT64NuT9IyXn90CDVXdCrhSEKc}}
      USER_ID: ${{ovFzt6nEDrUhWJBxsm5o6rm6nTBA}}
      START_DATE: ${{ 12-17 }}
      BIRTHDAY: ${{1999-12-17 }}
      CITY: ${{ 哈尔滨 }}
      USERS_ID: ${{ovFzt6nEDrUhWJBxsm5o6rm6nTBA}}
